import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import SidebarNav from '@/components/SidebarNav'
import MobileMenu from '@/components/MobileMenu'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans`}>
        <SidebarNav />
        <MobileMenu />
        <main className='ml-0 pt-20 md:ml-24 md:pt-10 px-6'>{children}</main>
      </body>
    </html>
  )
}
